{{- if .Values.rbac.enable }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: go-manager-role
rules:
- apiGroups:
  - pathfinder.runelabs.xyz
  resources:
  - starknetrpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pathfinder.runelabs.xyz
  resources:
  - starknetrpcs/finalizers
  verbs:
  - update
- apiGroups:
  - pathfinder.runelabs.xyz
  resources:
  - starknetrpcs/status
  verbs:
  - get
  - patch
  - update
{{- end -}}
