apiVersion: runelabs.xyz/v1alpha1
kind: StarknetNode
metadata:
  name: mainnet
  namespace: default
spec:
  network: "mainnet"
  snapshot:
    checksum: "ca80658d1b36f26db03a89fc2f9949ce2b5da0dd396c98ce8b3f3eab1d1c2fb2"
    file_name: "mainnet_0.16.0_1514518.sqlite.zst"
    storage:
      size: "128Gi"
      class: "pathfinder-expandable-storage-sepolia"
  l1_rpc_secret:
    name: mainnet-rpc-endpoint
    key: l1_rpc
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "4"
      memory: "8Gi"
  storage:
    size: "256Gi"
    class: "pathfinder-expandable-storage-sepolia"
---
apiVersion: v1
kind: Secret
metadata:
  name: mainnet-rpc-endpoint
type: Opaque
data:
  l1_rpc: "d3NzOi8vZXRoLW1haW5uZXQuZy5hbGNoZW15LmNvbS92Mi9CclI5czNvdFpoX3ZSWDdfRVhMSkJCOWxWVEpfQk0wXwo="
