apiVersion: pathfinder.runelabs.xyz/v1alpha1
kind: StarknetRPC
metadata:
  labels:
    app.kubernetes.io/name: go
    app.kubernetes.io/managed-by: kustomize
  name: starknetrpc-sample
spec:
  # TODO(user): Add fields here
